// tb_CimBlock.sv
// Testbench for Ternary CIM Block.
// Reads test data from files generated by gen_test_vectors.py.
// Writes simulation outputs to tests/sim_output.hex for verification.
//
// Pipeline latency (from cim_ren assertion to valid cim_odata): 2 cycles.
//   Cycle 0: drive cim_ren=1, cim_raddr=K (just after posedge)
//   Cycle 1: ClockGate enables rd_clock, SRAM reads row K, combinational compute
//   Cycle 2: cim_ren_reg=1, OutReg captures result → cim_odata valid
//
// Activation latency (from act_valid assertion to LUT ready): 2 cycles.
//   Cycle 0: drive act_valid=1
//   Cycle 1: CimBlock InputReg latches act_valid
//   Cycle 2: CimMacro LUT registers update
//   Testbench waits ACT_SETTLE=4 cycles after pulsing act_valid for margin.

`timescale 1ns/1ps

module tb_CimBlock;

    // -----------------------------------------------------------------------
    // Parameters
    // -----------------------------------------------------------------------
    localparam int N_GROUPS   = 16;
    localparam int DEPTH      = 32;
    localparam int ADDR_WIDTH = 5;
    localparam int ACT_SETTLE = 4;   // extra settle cycles after act_valid

    // 400 MHz clock (matches synthesis constraint T_CLK = 2.5 ns)
    localparam real CLK_HALF = 1.25;  // half-period in ns

    // -----------------------------------------------------------------------
    // DUT signals
    // -----------------------------------------------------------------------
    logic                       clk;
    logic                       reset;

    logic                       cim_wen;
    logic [ADDR_WIDTH-1:0]      cim_waddr;
    logic [5*N_GROUPS-1:0]      cim_wdata;      // 320-bit

    logic [24*N_GROUPS-1:0]     act_in;          // 1536-bit
    logic [7:0]                 zp_in;
    logic                       act_valid;

    logic                       cim_ren;
    logic [ADDR_WIDTH-1:0]      cim_raddr;

    logic [31:0]                cim_odata;
    logic                       cim_odata_valid;

    // -----------------------------------------------------------------------
    // DUT instantiation
    // -----------------------------------------------------------------------
    CimBlock #(
        .N_GROUPS  (N_GROUPS),
        .DEPTH     (DEPTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) dut (
        .clk            (clk),
        .reset          (reset),
        .cim_wen        (cim_wen),
        .cim_waddr      (cim_waddr),
        .cim_wdata      (cim_wdata),
        .act_in         (act_in),
        .zp_in          (zp_in),
        .act_valid      (act_valid),
        .cim_ren        (cim_ren),
        .cim_raddr      (cim_raddr),
        .cim_odata      (cim_odata),
        .cim_odata_valid(cim_odata_valid)
    );

    // -----------------------------------------------------------------------
    // Clock
    // -----------------------------------------------------------------------
    initial clk = 0;
    always #CLK_HALF clk = ~clk;

    // -----------------------------------------------------------------------
    // Test data memory (loaded from generated hex files)
    // -----------------------------------------------------------------------
    logic [79:0]    weight_mem [0:DEPTH-1];   // 32 rows × 80 bits
    logic [7:0]     act_bytes  [0:47];         // 48 uint8 activations
    logic [7:0]     zp_byte    [0:0];          // 1-byte zero point
    logic [31:0]    golden     [0:DEPTH-1];    // 128 × 32-bit golden outputs

    // Simulation result collection
    logic [31:0]    sim_results [0:DEPTH-1];
    integer         collected_count;
    integer         out_fd;

    // -----------------------------------------------------------------------
    // Task: apply reset
    // -----------------------------------------------------------------------
    task do_reset;
        begin
            reset     = 1;
            cim_wen   = 0;  cim_waddr  = '0;  cim_wdata = '0;
            act_in    = '0; zp_in      = '0;  act_valid = 0;
            cim_ren   = 0;  cim_raddr  = '0;
            repeat (8) @(posedge clk);
            #1;
            reset = 0;
            @(posedge clk); #1;
        end
    endtask

    // -----------------------------------------------------------------------
    // Task: write all DEPTH rows to CellArray SRAM
    // Protocol per row (CimBlock has InputReg that registers write signals):
    //   - Drive at #1 after posedge(N)
    //   - posedge(N+1): CimBlock InputReg latches → cim_wen_reg=1
    //   - ClockGate samples during low phase N+1→N+2 → en_latch=1
    //   - posedge(N+2): wr_clock=1, SRAM writes
    //   Hold cim_wen=1 for 3 posedge-to-posedge intervals to be safe.
    // -----------------------------------------------------------------------
    task write_all_weights;
        integer row;
        begin
            $display("[%0t] Writing %0d rows to SRAM...", $time, DEPTH);
            for (row = 0; row < DEPTH; row = row + 1) begin
                @(posedge clk); #1;
                cim_wen   = 1;
                cim_waddr = row[ADDR_WIDTH-1:0];
                cim_wdata = weight_mem[row];
                @(posedge clk); #1;   // registered in CimBlock
                @(posedge clk); #1;   // SRAM write completes
                cim_wen   = 0;
            end
            @(posedge clk); #1;  // settle
            $display("[%0t] SRAM write complete.", $time);
        end
    endtask

    // -----------------------------------------------------------------------
    // Task: load activations + ZP, pulse act_valid, wait for LUT settlement
    // -----------------------------------------------------------------------
    task load_activations;
        integer i;
        begin
            // Pack byte array into 1536-bit act_in
            // Layout: group i uses bytes [3*i*8 +: 24]
            //   act0_i = act_bytes[3*i], act1_i = act_bytes[3*i+1], act2_i = act_bytes[3*i+2]
            for (i = 0; i < 3*N_GROUPS; i = i + 1) begin
                act_in[8*i +: 8] = act_bytes[i];
            end
            zp_in = zp_byte[0];

            $display("[%0t] Loading activations, ZP=0x%02h", $time, zp_byte[0]);

            // Pulse act_valid for 1 cycle
            @(posedge clk); #1;
            act_valid = 1;
            @(posedge clk); #1;
            act_valid = 0;

            // Wait for LUT registers to be fully updated
            repeat (ACT_SETTLE) @(posedge clk);
            #1;
            $display("[%0t] LUT ready.", $time);
        end
    endtask

    // -----------------------------------------------------------------------
    // Task: sequentially read all DEPTH rows, collect 32-bit outputs.
    // Pipeline: assert cim_ren for DEPTH cycles + 2 drain cycles.
    //   cim_odata valid 2 cycles after cim_ren assertion.
    // -----------------------------------------------------------------------
    task read_all_rows;
        integer cyc;
        begin
            collected_count = 0;
            $display("[%0t] Reading %0d rows (2-cycle pipeline)...", $time, DEPTH);

            for (cyc = 0; cyc <= DEPTH + 1; cyc = cyc + 1) begin
                // Drive read port at negedge so cim_raddr is stable before the
                // next posedge activates rd_clock. Driving at posedge+#1 was
                // correct for CLK_HALF=1.0 (negedge coincidence) but incorrect
                // for CLK_HALF=1.25: cim_raddr would change 0.25 ns before the
                // negedge while rd_clock/RA6T latch is still transparent,
                // causing the latch to capture the next row's data instead.
                @(negedge clk); #0.1;
                if (cyc < DEPTH) begin
                    cim_ren   = 1;
                    cim_raddr = cyc[ADDR_WIDTH-1:0];
                end else begin
                    cim_ren   = 0;
                    cim_raddr = '0;
                end

                // Check output shortly after posedge (OutReg has updated).
                @(posedge clk); #0.1;

                // Capture when valid
                if (cim_odata_valid) begin
                    if (collected_count < DEPTH) begin
                        sim_results[collected_count] = cim_odata;
                        collected_count = collected_count + 1;
                    end
                end
            end

            $display("[%0t] Read complete. Collected %0d results.",
                     $time, collected_count);
        end
    endtask

    // -----------------------------------------------------------------------
    // Waveform dump
    // -----------------------------------------------------------------------
    initial begin
`ifdef FSDB
        $fsdbDumpfile("tb_CimBlock.fsdb");
        $fsdbDumpvars(0, tb_CimBlock);
        $fsdbDumpMDA();
`elsif VCD
        $dumpfile("tb_CimBlock.vcd");
        $dumpvars(0, tb_CimBlock);
`endif
    end

    // -----------------------------------------------------------------------
    // Main test body
    // -----------------------------------------------------------------------
    integer pass_count, fail_count, i;
    logic signed [31:0] got_s, exp_s;

    initial begin
        // Load generated test data
        $readmemh("tests/weight_mem.hex", weight_mem);
        $readmemh("tests/act_mem.hex",    act_bytes);
        $readmemh("tests/zp.hex",         zp_byte);
        $readmemh("tests/golden.hex",     golden);

        $display("============================================");
        $display("  Ternary CIM Testbench  N=%0d D=%0d", N_GROUPS, DEPTH);
        $display("============================================");

        do_reset();
        write_all_weights();

`ifdef SAIF
        // Single window covering the full inference (LUT build + compute).
        $set_toggle_region(dut);
        $toggle_start();
`endif
        load_activations();
        read_all_rows();
`ifdef SAIF
        $toggle_stop();
        $toggle_report("tests/sim.saif", 1.0e-9, "tb_CimBlock");
`endif

        // Write simulation outputs to file
        out_fd = $fopen("tests/sim_output.hex", "w");
        if (!out_fd) begin
            $display("ERROR: cannot open tests/sim_output.hex");
            $finish;
        end
        for (i = 0; i < collected_count; i = i + 1)
            $fdisplay(out_fd, "%08h", sim_results[i]);
        $fclose(out_fd);
        $display("[%0t] Output written to tests/sim_output.hex", $time);

        // In-testbench pass/fail comparison
        pass_count = 0; fail_count = 0;
        $display("\n--- Per-row comparison (showing first 16 and all failures) ---");
        for (i = 0; i < DEPTH; i = i + 1) begin
            got_s = $signed(sim_results[i]);
            exp_s = $signed(golden[i]);
            if (sim_results[i] === golden[i]) begin
                pass_count = pass_count + 1;
                if (i < 16)
                    $display("  Row %3d PASS  sim=%08h (%0d)", i, sim_results[i], got_s);
            end else begin
                fail_count = fail_count + 1;
                $display("  Row %3d FAIL  sim=%08h (%0d)  exp=%08h (%0d)",
                         i, sim_results[i], got_s, golden[i], exp_s);
            end
        end

        $display("\n============================================");
        $display("  PASS: %0d / %0d    FAIL: %0d",
                 pass_count, DEPTH, fail_count);
        if (fail_count == 0)
            $display("  *** ALL TESTS PASSED ***");
        else
            $display("  *** %0d FAILURES ***", fail_count);
        $display("============================================");

        $finish;
    end

    // Safety timeout (10 ms)
    initial begin
        #10_000_000;
        $display("ERROR: simulation timeout at %0t", $time);
        $finish;
    end

endmodule: tb_CimBlock
