#!/usr/bin/env python3
"""
verify_sim_output.py — Compare VCS simulation output with Ternary CIM golden.

Usage:
  python3 sim/verify_sim_output.py [sim/tests/sim_output.hex]

If no argument is given, defaults to sim/tests/sim_output.hex.
Compares against sim/tests/golden.hex (generated by gen_test_vectors.py).

Output format of sim_output.hex (written by tb_CimBlock.sv):
  One 8-digit lowercase hex value per line (32-bit 2's complement cim_odata).
  Lines starting with '//' or blank lines are ignored.

Exit code: 0 if all pass, 1 if any fail.
"""

import sys
from pathlib import Path

SIM_DIR    = Path(__file__).resolve().parent
TESTS_DIR  = SIM_DIR / 'tests'
GOLDEN_PATH = TESTS_DIR / 'golden.hex'
DEFAULT_SIM = TESTS_DIR / 'sim_output.hex'


def load_hex_file(path: Path) -> list:
    """Parse a hex file, one value per line, ignoring comment/blank lines."""
    vals = []
    for raw in path.read_text().splitlines():
        line = raw.split('//')[0].strip()
        if not line:
            continue
        vals.append(int(line, 16))
    return vals


def s32(u: int) -> int:
    """Convert unsigned 32-bit to signed Python int."""
    u &= 0xFFFF_FFFF
    return u - (1 << 32) if u >= (1 << 31) else u


def main():
    sim_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SIM

    # Sanity checks on file availability
    if not GOLDEN_PATH.exists():
        print(f'ERROR: golden.hex not found at {GOLDEN_PATH}')
        print('       Run  python3 sim/gen_test_vectors.py  first.')
        sys.exit(1)

    if not sim_path.exists():
        print(f'ERROR: simulation output not found at {sim_path}')
        print('       Run the VCS simulation first (make sim).')
        sys.exit(1)

    golden = load_hex_file(GOLDEN_PATH)
    sim    = load_hex_file(sim_path)

    print('=== Ternary CIM Simulation Verifier ===')
    print(f'  Golden  : {GOLDEN_PATH}  ({len(golden)} rows)')
    print(f'  Sim out : {sim_path}  ({len(sim)} rows)')

    if len(sim) != len(golden):
        print(f'\nERROR: row count mismatch — sim has {len(sim)}, golden expects {len(golden)}')
        sys.exit(1)

    DEPTH  = len(golden)
    passed = 0
    failed = 0

    print(f'\n--- Per-row comparison (first 16 rows + all failures) ---')
    for i in range(DEPTH):
        got = s32(sim[i])
        exp = s32(golden[i])
        ok  = (got == exp)

        if ok:
            passed += 1
            if i < 16:
                print(f'  Row {i:3d}  PASS  sim={got:12d}  (0x{sim[i] & 0xFFFF_FFFF:08x})')
        else:
            failed += 1
            print(f'  Row {i:3d}  FAIL  '
                  f'sim={got:12d} (0x{sim[i] & 0xFFFF_FFFF:08x})  '
                  f'exp={exp:12d} (0x{golden[i] & 0xFFFF_FFFF:08x})  '
                  f'err={got - exp}')

    print(f'\n{"=" * 50}')
    print(f'  PASS: {passed} / {DEPTH}    FAIL: {failed}')
    if failed == 0:
        print('  *** ALL TESTS PASSED ***')
        sys.exit(0)
    else:
        print(f'  *** {failed} FAILURE(S) ***')
        sys.exit(1)


if __name__ == '__main__':
    main()
